import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Texts",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider
            appearance={{
                variables: {
                    colorPrimary: '#2d7af7',
                    colorSuccess: 'green',
                    colorTextOnPrimaryBackground: 'white',
                    colorTextSecondary: '#ed13ba',
                    fontSize:'1.5rem',
                    borderRadius:'0.5rem',
                    spacingUnit:'1.3rem'
                }
            }}
        >
            <html lang='en'>
                <body className={`${inter.className} bg-dark-1`}>{children}</body>
            </html>
        </ClerkProvider>
    );
}